### ISSUE TITLE
Bug: causes the IDE to always stay on "Analyzing" for many/all classes

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Miha-x64/Mikes_IDEA_extensions#26]
After updating to this version of the IDE:

Android Studio Chipmunk | 2021.2.1
Build #AI-212.5712.43.2112.8512546, built on April 28, 2022

It seems that in a large project I work on, it keeps showing "Analyzing" for various classes, and never finishes.

I thought it's an issue on the IDE, so reported here:
https://issuetracker.google.com/issues/232107687

After trying to disable the current addon, it seems that the issue is gone, so this means it's something related to the addon.

I wish I could somehow filter the inspections of the addon (write "mike" for example), to see which one might be causing it, but sadly there is no such a thing.

**Comment by Miha-x64** [comment]
Can you share that thread dump with me? It has restricted access on Google issue tracker.

**Comment by Miha-x64** [comment]
There's no single `mike` in your thread dumps. So it's not my fault 😀

**Comment by AndroidDeveloperLB** [comment]
@Miha-x64 And still, only when I enable the plugin I see this issue. And I always see this issue when I enable the plugin.
It stays on "Analyzing" forever on many (or maybe all) classes.

**Comment by Miha-x64** [comment]
Can you find which version causes this, please?
https://plugins.jetbrains.com/plugin/12690-mike-s-idea-extensions/versions

**Comment by AndroidDeveloperLB** [comment]
Here's the full information from the IDE after enabling the plugin and restarting the IDE (to reproduce the issue) :

Android Studio Chipmunk | 2021.2.1 Patch 1
Build #AI-212.5712.43.2112.8609683, built on May 18, 2022
Runtime version: 11.0.12+7-b1504.28-7817840 amd64
VM: OpenJDK 64-Bit Server VM by Oracle Corporation
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 8048M
Cores: 12
Registry: external.system.auto.import.disabled=true, debugger.watches.in.variables=false
Non-Bundled Plugins: com.intellij.marketplace (212.5712.51), com.dubreuia (2.3.0), org.intellij.plugins.markdown (212.5457.16), com.github.beansoft.jadx.gui.idea (2021.2.1), Show As ... (1.0.3), GenerateSerializationHelpers (1.0.6), org.jetbrains.kotlin (212-1.6.21-release-334-AS5457.46), izhangzhihao.rainbow.brackets (6.23), com.ppismerov.ksvu (0.0.1), com.google.mad-scorecard (1.2), net.aquadc.mike.plugin (0.22), GenerateSerialVersionUID (3.0.3), String Manipulation (9.4.1)

**Comment by Miha-x64** [comment]
Thanks to @vadiole for the stack trace:
```
java.lang.IncompatibleClassChangeError: Method 'com.android.tools.idea.gradle.project.model.AndroidModuleModel com.android.tools.idea.gradle.project.model.AndroidModuleModel.get(org.jetbrains.android.facet.AndroidFacet)' must be InterfaceMethodref constant
 at net.aquadc.mike.plugin.android.res.UnsupportedAttrInspection$buildVisitor$1.visitFile(UnsupportedAttrInspection.kt:67)
 at com.intellij.psi.impl.source.xml.XmlFileImpl.accept(XmlFileImpl.java:57)
 at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:64)
 at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:55)
 at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:326)
 at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$4(LocalInspectionsPass.java:285)
 at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:159)
 at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:151)
 at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$5(LocalInspectionsPass.java:283)
 at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:130)
 at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:119)
 at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$6(LocalInspectionsPass.java:283)
 at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:136)
 at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
 at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
 at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
 at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:92)
 at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
 at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
 at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
 at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:104)
 at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:86)
 at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
 at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
 at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
 at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
 at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
 at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by vadiole** [comment]
btw my problem on the video

https://user-images.githubusercontent.com/48314952/170558342-b7921eb6-491c-4f85-ad2e-ed1baf549356.mov

**Comment by AndroidDeveloperLB** [comment]
I don't understand what you guys are talking about. Are you sure it's the same issue?

**Comment by vadiole** [comment]
Sort of. Maybe. By the way, you can look at the studio logs and try to find the error there. Help -> show logs in finder for Mac OS

**Comment by AndroidDeveloperLB** [comment]
I have Windows OS, and I've already shared the logs.

**Comment by AndroidDeveloperLB** [comment]
@vadiole See what I wrote here:
https://github.com/Miha-x64/Mikes_IDEA_extensions/issues/26#issuecomment-1131696074

**Comment by vadiole** [comment]
Are thread dumps and logs the same thing?😳

**Comment by AndroidDeveloperLB** [comment]
@vadiole I chose on the IDE "Collect logs and Diagnostic data", as this is what Google often said to use.

**Comment by AndroidDeveloperLB** [comment]
@Miha-x64 You've succeeded to reproduce what I've explained?

**Comment by Miha-x64** [comment]
Of course no, I don't have Android Studio and not going to download it.

**Comment by AndroidDeveloperLB** [comment]
@Miha-x64 I don't understand how it's possible. You've developed a plugin to an IDE you don't test on?!

**Comment by Miha-x64** [comment]
Don't worry. You could reopen the issue if it will reproduce with the new plugin version.

**Comment by AndroidDeveloperLB** [comment]
I don't understand what's going on. You fixed it, but you say you didn't reproduce it as you don't have Android Studio?
How do you know you've fixed it, then?
