### ISSUE TITLE
java.lang.NoSuchMethodError: 'java.util.List org.jetbrains.uast.UDeclaration.getAnnotations()'

### ISSUE THREAD

**Issue by BorzdeG** [Miha-x64/Mikes_IDEA_extensions#7]
IntelliJ IDEA 2021.2
Build #IU-212.4746.92, built on July 27, 2021

```
java.lang.NoSuchMethodError: 'java.util.List org.jetbrains.uast.UDeclaration.getAnnotations()'
	at net.aquadc.mike.plugin.android.TargetApiInspection$uVisitor$1.visitDeclaration(TargetApiInspection.kt:26)
	at org.jetbrains.uast.visitor.UastVisitor$DefaultImpls.visitVariable(UastVisitor.kt:15)
	at org.jetbrains.uast.visitor.AbstractUastNonRecursiveVisitor.visitVariable(UastVisitor.kt:128)
	at org.jetbrains.uast.visitor.UastVisitor$DefaultImpls.visitParameter(UastVisitor.kt:16)
	at org.jetbrains.uast.visitor.AbstractUastNonRecursiveVisitor.visitParameter(UastVisitor.kt:128)
	at org.jetbrains.uast.UParameter$DefaultImpls.accept(UVariable.kt:80)
	at org.jetbrains.uast.UParameterEx$DefaultImpls.accept(UVariable.kt)
	at org.jetbrains.uast.kotlin.KotlinUParameter.accept(KotlinUVariable.kt:177)
	at com.intellij.uast.UastVisitorAdapter.visitElement(UastVisitorAdapter.java:32)
	at org.jetbrains.kotlin.psi.KtElementImplStub.accept(KtElementImplStub.java:63)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:64)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:55)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:326)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$4(LocalInspectionsPass.java:285)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:159)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:151)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$5(LocalInspectionsPass.java:283)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:130)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:119)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$6(LocalInspectionsPass.java:283)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:136)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:92)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:104)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:83)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:183)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:83)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by Miha-x64** [comment]
Yeps, same happens to me with new IDEA, too. Thanks, will fix.
